force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Registration Open</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WebinarHandler.cls
/**
 * Created by pbura on 10/18/2021.
 */



public with sharing class WebinarHandler {


    public static void handleCostChange(List<Webinar__c> webinars){
        for(Webinar__c web : webinars){
            if(web.Cost__c < 100){
                web.Approval_Status__c = 'Approved';
            }
        }

    }


    public static void handleRejectedWebinars(List<Webinar__c> webinars){
        for(Webinar__c web : webinars){
            if( web.Approval_Status__c=='Rejected'){
                web.Status__c = 'Canceled';

            }
        }

    }


    /* public static void statusChange(Map<Id, Webinar__c> oldWebinar, Map<Id, Webinar__c>newWebinar){





    }*/

    public static void handleBeforeInsert(List<Webinar__c> webinars){
        handleCostChange(webinars);
        handleRejectedWebinars(webinars);

    }

    public static void handleBeforeUpdate(List<Webinar__c> webinars) {
        handleCostChange(webinars);
        handleRejectedWebinars(webinars);

    }

}